### ISSUE TITLE
Locale territory should be capitalized.

### ISSUE THREAD

**Issue by oscarni** [san650/web-app-manifest-validator#7]
This validator throws an error when lang country is written with capital letters, eg `en-US`. Looks like thats the preferred way according to the specs https://w3c.github.io/manifest/#lang-member

Tests pass when a lang is written in all lowercase `en-us`.

**Comment by oscarni** [comment]
Never mind! The fault was on my end, it works with `en-US`. Although it's not enforced. Not sure if it matters 🤷‍♂️

**Comment by san650** [comment]
@oscarni thanks for checking this, if `en-US` format is preferred over `en-us`, we can always show a warning stating this. What do you think? Is it worth it?
